### ISSUE TITLE
Vash?

### ISSUE THREAD

**Issue by kirbysayshi** [nufyoot/kally-razor#6]
Saw a push to NPM. Building your own is of course fun, but did you see [Vash](https://github.com/kirbysayshi/vash)? Just curious what, in the event you had seen it, was deficient? Either way, good luck. Razor syntax has it's tricky edge cases.

**Comment by nufyoot** [comment]
Thanks for the insight mate!  Seriously, there's nothing "deficient" in Vash (yes, I had seen it and many other alternatives).  There's a few reasons I went with writing my own and none of them stem from "deficiencies" so to speak.

First, it's an excellent exercise for me to try my hand at parsing a mixed mode file, especially when the current mode can be clear (like using @() or @{ }) or completely ambiguous (like creating an if statement where the body of that statement can be Javascript AND HTML mixed together).

Second, KallyRazor is merely just an alternative to what already exists.  There are times when we want the holy grail library that does it all, and then there are times where we want to pick the one that fits our needs best.  Vash is very well thought out and implemented extremely well!  I actually started using it for a website that I was doing.  But, in the end, I wanted something different.  Not necessarily something "more" where I could contribute to what Vash already has, but something different.

So, I wish you the best of luck on Vash, and don't change a thing just because there's yet another Razor library for Node.js!  Vash has a specific audience and KallyRazor just has myself right now.  If I end up converting someone else to use KallyRazor that's great, but it is first and foremost a tool that I plan on using myself.

**Comment by kirbysayshi** [comment]
Well cool, building your own is certainly a great learning resource (that's why I initially built Vash)!

I mostly ask because I'm continually looking for what would help users of Vash, and if there was something you really wished it did better (or differently), I'd love to know.

P.S. I found going from things like `@model.what` to `@model.what.forEach(function(a){ <li>@a</li> })` to be pretty tricky as Vash evolved.

**Comment by nufyoot** [comment]
Absolutely!  It will be neat to watch things mature with time.  I'm looking forward to all the difficulties involved in parsing all of Razor.  It's something I will probably learn the most from.
